// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        mavenCentral() // It's good practice to add mavenCentral() as well
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.4.0'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral() // It's good practice to add mavenCentral() as well
    }
}
