apply plugin: 'com.android.application'

android {
    compileSdkVersion 33
    namespace "org.softosaurus.reactionspeed"
    defaultConfig {
        applicationId "org.softosaurus.reactionspeed"
        minSdkVersion 21
        targetSdkVersion 33
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }
}

dependencies {
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'com.google.android.gms:play-services-ads:23.0.0'
}
